import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navbar from "./navbar";

const useUser = () => ({ user: null });

export default function Home() {
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.replace("/");
      console.log("user not exits");
    } else {
      router.push("/login");
    }
  }, [router, user]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-auto h-screen  max-w-[1440px]">
        <div className="mx-auto mt-8 h-[691px] w-[576px] rounded-[20px] border-2 px-[60px] pt-8">
          <form action="post">
            <h1 className="pb-6 text-center text-[32px] font-semibold">
              Create your account
            </h1>
            <label htmlFor="name">
              Name
              <input
                type="text"
                placeholder="Enter"
                className="mb-7 mt-2 w-full rounded-[6px] border px-4 py-3 "
              />
            </label>
            <label htmlFor="email">
              Email
              <input
                type="email"
                placeholder="Enter"
                className="mb-7 mt-2 w-full rounded-[6px] border px-4 py-3 "
              />
            </label>
            <label htmlFor="password">
              Password
              <input
                type="password"
                placeholder="Enter"
                className="mb-7 mt-2 w-full rounded-[6px] border px-4 py-3 "
              />
            </label>

            <button className="mt-4 h-[56px] w-[456px] rounded-[6px] bg-black text-white">
              CREATE ACCOUNT
            </button>
          </form>

          <p className="my-10 text-center text-[#333]">
            Have an Account?
            <span className="ml-3 font-medium">
              <Link href="/login">LOGIN</Link>
            </span>
          </p>
        </div>
      </main>
    </>
  );
}
